### ISSUE TITLE
Not receiving clipboard in some cases

### ISSUE THREAD

**Issue by Aymkdn** [felipecrs/clipboard-sync#21]
Hi,

Thanks for this tool.

On a Windows 11 computer, when I copy something in my clipboard, I can see the icon with the upload arrow, and then in the OneDrive folder I can see the file created that contains my text.
On the other computer (Windows 10), the icon doesn't show the download arrow, and it seems it doesn't pick the new created file at all.

I checked and the Win 10 computer has the correct folder selected (right click -> open folder). Is there a debug mode I can activate to check what's going on? Any idea why this instance doesn't detect the new file?

They both run the last available version of your app.

**Comment by felipecrs** [comment]
Hey, thanks for the report.

Can you confirm that the file is being downloaded by OneDrive in your Windows 10 computer? Also, please ensure to right click the folder and select "Always keep on this device":

![image](https://github.com/felipecrs/clipboard-sync/assets/29582865/8c816a9a-37b6-4cdb-b2fc-73d76948e2fe)

**Comment by Aymkdn** [comment]
Thanks for the quick reply!

Yes, the file is correctly downloaded on the Win 10 computer, and the folder is mark as "Always keep on this device"

**Comment by felipecrs** [comment]
Is Clipboard Sync on Windows 10 correctly uploading clipboards as well?

> Is there a debug mode I can activate to check what's going on?

There is no easy way... as of now. :(

**Comment by Aymkdn** [comment]
> Is Clipboard Sync on Windows 10 correctly uploading clipboards as well?

Yes, the other way around works: if I copy something on Windows 10, I can see the arrow up on the icon, the file is created, and I can see the arrow down on Windows 11.

**Comment by felipecrs** [comment]
Hm... that's interesting. I would say there is something wrong with the filewatcher.

Can you try downgrading to [0.7.13](https://github.com/felipecrs/clipboard-sync/releases/tag/v0.7.13) on Windows 10?

0.8.0 uses a different filewatcher than 0.7.13 does.

**Comment by Aymkdn** [comment]
It seems to work with v0.7.13 on Windows 10!

**Comment by felipecrs** [comment]
Ok... keep using that for now then. I'll refactor this logic, and once you can test a new version I'll let you know.

**Comment by Aymkdn** [comment]
Sounds good. Thanks

**Comment by felipecrs** [comment]
Fixed by 754b98759823a3340c524edf536aa19e3e7efee3, released as [v0.8.1](https://github.com/felipecrs/clipboard-sync/releases/tag/v0.8.1).

I have a [major improvement incoming](https://github.com/felipecrs/clipboard-sync/pull/22), but for now you can safely upgrade to 0.8.1.

**Comment by Aymkdn** [comment]
It looks like this v0.8.1 works with Windows 10 :-) Thank you!

**Comment by felipecrs** [comment]
Thanks for confirming, but just for completeness, the issue isn't exactly because of Windows 10. On my Windows 10, Clipboard Sync was working fine. Maybe the version within Windows 10 or something else, but it doesn't matter as it was fixed anyway. :)

**Comment by felipecrs** [comment]
@Aymkdn just to inform you, [v0.9.0](https://github.com/felipecrs/clipboard-sync/releases/tag/v0.9.0) makes changes again on the file watching library.

The new one should be much more reliable than before, and this time it should not cause any issues to you.

When you have some time, and if you are still using Clipboard Sync, I'd appreciate your feedback. Thanks!

**Comment by Aymkdn** [comment]
I installed the last version (0.10.2) and nothing works anymore…

I reinstalled v0.9.0 and everything is working again!

**Comment by felipecrs** [comment]
That's really weird, as it's working for me. But I'll investigate.

**Comment by Aymkdn** [comment]
Thanks for the follow up. I'm on vacation for two weeks. I'll give it a try when I'm back!

**Comment by Aymkdn** [comment]
> Would you mind checking if 0.10.1 works?

I did a quick test, and so far it seems to be working (v0.10.2) 👍

**Comment by felipecrs** [comment]
Great then!
