### ISSUE TITLE
[BUG] A JavaScript error occurred in the main process after select saving path.

### ISSUE THREAD

**Issue by HumanMus1c** [felipecrs/clipboard-sync#37]
![image](https://github.com/felipecrs/clipboard-sync/assets/46023154/899844cc-dddd-4857-b67d-57b0d19ea069)
[Squirrel-Shortcut.log](https://github.com/felipecrs/clipboard-sync/files/14110651/Squirrel-Shortcut.log)

**Comment by felipecrs** [comment]
Thanks for reporting. The only piece of code that contacts external servers in this app is to check for updates at initialization.

I know how to improve it.

Does the application crash (does it exit)? Or does it continue to work after that?

**Comment by HumanMus1c** [comment]
> Thanks for reporting. The only piece of code that contacts external servers in this app is to check for updates at initialization.
> 
> I know how to improve it.
> 
> Does the application crash (does it exit)? Or does it continue to work after that?

It doesn't crash, and it keeps error every time app starting and other action.

**Comment by felipecrs** [comment]
Alright. I should release a fix later today or early tomorrow.

**Comment by felipecrs** [comment]
@HumanMus1c please test if v0.10.4 fixes your issue.

**Comment by HumanMus1c** [comment]
> @HumanMus1c please test if v0.10.4 fixes your issue.

Thank you for your effort and this error has fixed on v0.10.5.
