### ISSUE TITLE
Support macOS

### ISSUE THREAD

**Issue by colinleefish** [felipecrs/clipboard-sync#40]
Hi! Syncing clipboard across devices is a very much needed feature for people working on multiple devices. Thank you for working on such a great idea!

By the way, do you have plan to make it cross platform? Currently it looks kinda weird on macOS.

<img width="662" alt="image" src="https://github.com/felipecrs/clipboard-sync/assets/3325804/43f74f09-ad13-41a5-ada2-d71baa964b53">

Thanks!

**Comment by felipecrs** [comment]
Thank you.

Yeah, I sure want to support other platforms, I just didn't have a need so far.

It should not be too difficult to make it work on macOS. I'll keep this issue posted if I have news.

**Comment by felipecrs** [comment]
A bit of news:

- https://github.com/felipecrs/clipboard-sync/pull/41
  - This is a step towards cross platform

Other things I believe will be necessary:

- Ensure fswin is only imported and called in Windows platform
- Fix the icon for macOS as it should not be .ico there

**Comment by Perchycs** [comment]
Just commenting to agree with Colinleefish. I am very keen to have a cross-platform clipboard sync as it is currently such a pain syncing between mac and windows.

Thanks!

**Comment by felipecrs** [comment]
Support for macOS at this point is only a matter of fixing the tray icon.

Looks like it requires a special Template.png: https://www.electronjs.org/docs/latest/api/tray#:~:text=)%0A%7D)-,MacOS,-Icons%20passed%20to

I just didn't add support yet because I don't have a macOS environment to test, but I can try making the changes and asking someone to test.

**Comment by felipecrs** [comment]
@colinleefish @Perchycs [v0.12.0](https://github.com/felipecrs/clipboard-sync/releases/tag/v0.12.0) adds support for macOS. Please give it a try. :D
