### ISSUE TITLE
Enhancement: add Android client

### ISSUE THREAD

**Issue by lammel-hub** [felipecrs/clipboard-sync#54]
Your app is a wonderful solution to this much needed functionality!

I do not know enough programming to know if this fearure request is unrealistic, but I do already have a working sync between 2 PCs and an android phone (not GDrive) so in principle it should work.

**Comment by felipecrs** [comment]
I find this idea super cool indeed, but unfortunately the libraries used to make this package a reality has no support for Android. Some of them don't even have support for Linux Desktop.

Perhaps an even bigger problem is that I use Electron to build this application, which has no support for Android.

If the application was made with something like Flutter, there would be a bigger chance to work, but last time I checked Flutter also doesn't have everything this project needs as library (like a clipboard event monitor).

Anyway, everything is doable, I just don't have the energy to make it a reality. 😞

**Comment by lammel-hub** [comment]
Thank you for your swift and honest response, much appreciated!

26 Apr 2024 15:58:38 Felipe Santos ***@***.***>:

**Comment by lammel-hub** [comment]
Thank you for the clarification. I am hapoy with the "maybe someday" for now 👍

26 Apr 2024 17:04:43 Felipe Santos ***@***.***>:

**Comment by felipecrs** [comment]
That's awesome news! I had never thought of trying KDE Connect for clipboard syncing.

Just to clarify, KDE Connect doesn't compete with this application anyhow.

If KDE Connect works for you, even between desktop devices, you should prefer KDE Connect for sure.

However, this application is meant for situations in which KDE Connect would not be suitable for, like for example syncing between computers between different networks without having to open any ports, through a file sync mechanism like OneDrive.

**Comment by lammel-hub** [comment]
Ah, you are right! True, they are different use cases in that sense 👍

1 maj 2024 04:28:07 Felipe Santos ***@***.***>:

**Comment by lammel-hub** [comment]
Hi again
I've played around a bit with KDE Connect now and they have implemented a simple solution that does not require an active monitoring of changes to the Android clipboard.

(See attached svreen shots)
1. Mark any text anywhere in Android
2. Select "share" via long-click and select KDE Connect (the text is then copied to the KDE app by Android)
3. In KDE: select which other device to copy the text string to

In your use case steps 1-2 would be the same (being built into Android by default) and then step 3 would instead be "copy text string to 'shared cloud clipboard file' for other devices to read as new/changed"

I know it is a bit more clunky than a proper copy-paste, but it would avoid the need for that missing lib to read the Android clipboard.

This is FYI only, as it hopefully can be useful as inspiration if you do look into it in the future.

/thanks for your patience with me

1 maj 2024 04:28:07 Felipe Santos ***@***.***>:

**Comment by lammel-hub** [comment]
![Screenshot_2024-05-04-21-50-07-479_net cozic joplin~2](https://github.com/felipecrs/clipboard-sync/assets/145585121/8757851f-3015-4674-a01c-96e4312df199)
![Screenshot_2024-05-04-21-50-29-627_android~2](https://github.com/felipecrs/clipboard-sync/assets/145585121/2cef3734-1244-4e18-8392-ecb67eab84bc)
![Screenshot_2024-05-04-21-50-52-662_org kde kdeconnect_tp~2](https://github.com/felipecrs/clipboard-sync/assets/145585121/efb2acc7-3e3e-497f-9f65-02337fab89c1)

**Comment by felipecrs** [comment]
That's a smart workaround. Thanks for letting me know.
